//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public int VisitorId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime EntryAt { get; set; }
        public System.DateTime ExitAt { get; set; }
        public string VisitPurpose { get; set; }
        public string Note { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
